### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by LISI0037** [valeoai/WaffleIron#15]
hello, 
Thank your your research! Your work is great! 
But I met some problems. I'm currently using the pytorch 1.11+cu113 as the readme said. My cuda version is 11.6. But when I try to do the training, I met the error:
```
0%|                                                  | 0/6377 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/home/users/Li/baseline_dataset/WaffleIron/launch_train.py", line 372, in <module>
    main(args, config)
  File "/home/users/Li/baseline_dataset/WaffleIron/launch_train.py", line 299, in main
    torch.multiprocessing.spawn(
  File "/home/users/Li/.conda/envs/waffleiron/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/users/Li/.conda/envs/waffleiron/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/users/Li/.conda/envs/waffleiron/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/users/Li/.conda/envs/waffleiron/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/users/Li/baseline_dataset/WaffleIron/launch_train.py", line 253, in distributed_training
    mng.train()
  File "/home/users/Li/baseline_dataset/WaffleIron/utils/trainer.py", line 290, in train
    self.one_epoch(training=True)
  File "/home/users/Li/baseline_dataset/WaffleIron/utils/trainer.py", line 177, in one_epoch
    loss = self.loss(out, labels)
  File "/home/users/Li/baseline_dataset/WaffleIron/utils/metrics.py", line 58, in __call__
    loss += self.lovasz_weight * lovasz_softmax_flat(
  File "/home/users/Li/baseline_dataset/WaffleIron/utils/lovasz.py", line 214, in lovasz_softmax_flat
    losses.append(torch.dot(errors_sorted, Variable(lovasz_grad(fg_sorted))))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSdot(handle, n, x, incx, y, incy, result)`
```
Can you help me with this? I run with three A100(40GB). I think maybe it's not the cuda version problem? because my version is 11.6 and torch only need the 11.3? 

>

**Comment by LISI0037** [comment]
Problem solved. Using torch>=2.0.

**Comment by gpuy** [comment]
Hi, happy to see you already solved the problem with pytorch >= 2.0. Up to now, I have never encoutered issue in the lovasz loss. If it occurs again with pytorch >= 2.0, let me know about it as well as the command to launch to reproduce it. Cheers, Gilles
